Add housekeeping jobs
blutspende/skeleton pull request #40
Opened 2024-07-17 14:38 UTC by balazsmate

2024-07-18 10:22 UTC, robert-hegedus-hero approved these changes

2024-07-22 11:29 UTC, attilarickert93 requested changes

2024-07-22 11:29 UTC, attilarickert93 commented on repository_analysis.go
> +	err = r.deleteAnalysisRequestExtraValuesByAnalysisRequestIDs(ctx, analysisRequestIDs)
pls delete the related items in a transaction

2024-08-28 14:55 UTC, attilarickert93 requested changes

2024-08-28 14:55 UTC, attilarickert93 commented on repository_analysis.go
> +	query := fmt.Sprintf(`DELETE FROM %s.sk_cerberus_queue_items WHERE queue_item_id IN
only remove successfully sent ones

2024-08-28 14:55 UTC, attilarickert93 commented on repository_analysis.go
> +	query := fmt.Sprintf(`SELECT id FROM %s.sk_analysis_requests WHERE valid_until_time < timezone('utc', now()) AND is_processed LIMIT $1;`, r.dbSchema)
would be nice to keep those which have been used, either if it has been used to sent an order msg to instrument, either if it was paired to with a result

2024-08-28 14:55 UTC, attilarickert93 commented on skeleton.go
> +	s.cleanupAnalysisResults()
unused analysis requests can be deleted, thats fine, but im not sure if results and queue items should be deleted over time at all, without making backup

i'd personally prefer some kind of archive mechanism that would copy the old data to a different archive db before deleting, either manually, either automatically. 
imho manual backup once per (half)year would be enough to keep the db size reasonable, performance shouldn't be affected much due to these tables growing over time

2024-09-18 11:27 UTC, attilarickert93 approved these changes

2024-09-18 11:37 UTC, merged